name : ci/cd pipeline

on:
  push :
    branches : ["main"]

jobs:
  build-the-application-module:

    runs-on : ubuntu-latest

    steps:

      - name : Downolod from the repo
        uses : actions/checkout@v4

      - name : Downolod the node.js
        uses : actions/setup-node@v4
        with :
         node-version : 20

      - name : Install packages
        run: cd frontend && npm ci

      - name : Build the application
        run : cd frontend && npm ci && npm run build


