name : ci/cd pipeline

on:
  push :
    branches : ["main"]

jobs:
  build-the-application-module:

    runs-on : ubuntu-latest

    steps:

      - name : Downolod from the repo
        uses : action/checkout@v4

      - name : Downolod the node.js
        uses : action/setup-node@v4
        with :
         node-version : 20

      - name : Install packages
        run: npm i

      - name : Build the application
        run : npm run build


